Feature/fit benchmark
Comrade-Software-Ltda/comrade-intl-net6 pull request #32
Opened 2022-09-29 17:50 UTC by yakkumo

2022-09-30 18:14 UTC, pedroLFaria requested changes
Diminua o PR

2022-10-07 22:58 UTC, pedroLFaria requested changes

2022-10-07 22:58 UTC, pedroLFaria commented on src/Comrade.Api/appsettings.Development.json
> +      "name": "Notifica��o - Mosele Software Consulting",
Esses caracteres aqui estão quebrados?

2022-10-07 22:58 UTC, pedroLFaria commented on src/Comrade.Api/appsettings.Development.json
> +    "SystemUser": false,
Qual foi o motivo para desativar todas essas features do projeto?

2022-10-07 22:58 UTC, pedroLFaria commented on src/Comrade.Domain/Models/Airplane.cs
> +
E essa linha em branco aqui?

2022-10-08 01:24 UTC, abraaoribeiro23 commented on src/Comrade.Api/appsettings.Development.json
> +      "name": "Notifica��o - Mosele Software Consulting",
Corrigido.

2022-10-08 01:24 UTC, abraaoribeiro23 commented on src/Comrade.Api/appsettings.Development.json
> +    "SystemUser": false,
Ativei novamente as features

2022-10-10 22:40 UTC, pedroLFaria requested changes

2022-10-10 22:40 UTC, pedroLFaria commented on src/Comrade.Persistence.ADO/CreateDatabase.cs
> +        var myConn =
Esse carinha está estranho, porque está sendo usado uma string de conexão fixa para o banco de dados aqui?

2022-10-11 02:50 UTC, abraaoribeiro23 commented on src/Comrade.Api/Controllers/V1/TenantSelectorApi/TenantSelectorController.cs
> +// [Authorize]
removi o authorize. Nesse momento ele não precisa existir

2022-10-11 03:32 UTC, abraaoribeiro23 commented on src/Comrade.Api/Controllers/V1/TenantSelectorApi/TenantSelectorController.cs
> +}
Última linha adicionada. Vou adicionar em outro PR a configuração do editorconfig pra usarmos esse padrão

2022-10-11 03:32 UTC, abraaoribeiro23 commented on src/Comrade.Persistence.ADO/MigratorTenantInfo.cs
> +}
adicionada

2022-10-11 03:33 UTC, abraaoribeiro23 commented on tests/Comrade.Benchmark/LinqBenchmark.cs
> +    public int LinqWhereAndFirst() =>
Sim, o jhoni optou por manter esse exemplo no projeto por enquanto pra estimar as pessoas a usá-lo para fazer testes durante o desenvolvimento

2022-10-11 03:37 UTC, abraaoribeiro23 commented on src/Comrade.Persistence.ADO/GetAllDatabases.cs
> +        using(var con = new SqlConnection("Server=(localdb)\\mssqllocaldb;Trusted_Connection=True;MultipleActiveResultSets=true"))
pode manter esse carinha no projeto por enquanto, vou migrálo para outro projeto de exemplo

2022-10-11 03:37 UTC, abraaoribeiro23 commented on src/Comrade.Persistence.ADO/CreateDatabase.cs
> +        var myConn =
pode manter esse carinha no projeto por enquanto, vou migrálo para outro projeto de exemplo

2022-10-12 03:44 UTC, abraaoribeiro23 approved these changes

2022-10-13 14:48 UTC, pedroLFaria approved these changes

2022-10-13 14:49 UTC, merged